basePath: /
definitions:
  models.Item:
    properties:
      description:
        type: string
      itemCode:
        type: string
      lineItemId:
        type: integer
      orderId:
        type: integer
      quantity:
        type: integer
    type: object
  models.Order:
    properties:
      customerName:
        type: string
      items:
        items:
          $ref: '#/definitions/models.Item'
        type: array
      orderId:
        type: integer
      orderedAt:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: indra.wijaya2303@gmail.com
    name: Indra Wijaya
  description: This is a sample API for hacktiv8-go Assignment 2
  title: hacktiv8-go Assignment 2 API
  version: "1.0"
paths:
  /orders:
    get:
      consumes:
      - application/json
      description: List all orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Order'
            type: array
      summary: List orders
      tags:
      - orders
    post:
      consumes:
      - application/json
      description: Create new order
      parameters:
      - description: Order Detail
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/models.Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Order'
      summary: Create order
      tags:
      - orders
  /orders/{orderId}:
    delete:
      consumes:
      - application/json
      description: Delete order by orderId
      parameters:
      - description: Order ID
        in: path
        name: orderId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete order
      tags:
      - orders
    put:
      consumes:
      - application/json
      description: Update order by orderId
      parameters:
      - description: Order ID
        in: path
        name: orderId
        required: true
        type: integer
      - description: Order Detail
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/models.Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update order
      tags:
      - orders
swagger: "2.0"
